name: format_conv
description: Cross-platform format conversion tool
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  flutter_riverpod: ^2.4.9
  path: ^1.8.0
  shared_preferences: ^2.2.2
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  msix: ^3.16.0

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 700

msix_config:
  display_name: Format Converter
  publisher_display_name: FormatConv
  identity_name: com.formatconv.app
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
